// Code generated by "stringer -type Status -linecomment"; DO NOT EDIT.

package status

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Completed-1]
	_ = x[Aborted-2]
	_ = x[Skipped-3]
}

const _Status_name = "unknown statuscompletedabortedskipped"

var _Status_index = [...]uint8{0, 14, 23, 30, 37}

func (i Status) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Status_index)-1 {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[idx]:_Status_index[idx+1]]
}
