// Code generated by "stringer -type Severity -linecomment"; DO NOT EDIT.

package severity

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Critical-1]
	_ = x[Warning-2]
	_ = x[Info-3]
}

const _Severity_name = "unknowncriticalwarninginfo"

var _Severity_index = [...]uint8{0, 7, 15, 22, 26}

func (i Severity) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Severity_index)-1 {
		return "Severity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Severity_name[_Severity_index[idx]:_Severity_index[idx+1]]
}
